"""add_audit_logs_and_timestamp_fields

Revision ID: 9ec7164f8edc
Revises: ea67b48b7626
Create Date: 2026-06-16 20:56:56.306313

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec7164f8edc'
down_revision: Union[str, None] = 'ea67b48b7626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='auditaction'), nullable=False),
    sa.Column('performed_by', sa.String(length=50), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_performed_by', 'audit_logs', ['performed_by'], unique=False)
    op.add_column('bugs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bugs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bugs', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('bugs', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('projects', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('updated_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_by')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('projects', 'updated_by')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('bugs', 'updated_by')
    op.drop_column('bugs', 'created_by')
    op.drop_column('bugs', 'updated_at')
    op.drop_column('bugs', 'created_at')
    op.drop_index('ix_audit_logs_performed_by', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
